shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - devtools
  - '!examples/**'

catalog:
  '@antfu/eslint-config': ^8.1.1
  '@nuxt/content': ^3.12.0
  '@nuxt/devtools': 4.0.0-alpha.3
  '@nuxt/devtools-kit': 4.0.0-alpha.3
  '@nuxt/eslint': ^1.15.2
  '@nuxt/kit': ^4.4.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/test-utils': ^4.0.2
  '@nuxtjs/sitemap': ^8.0.9
  '@vueuse/core': ^14.2.1
  better-sqlite3: ^12.8.0
  bumpp: ^11.0.1
  consola: ^3.4.2
  diff: ^8.0.4
  eslint: ^10.2.0
  eslint-plugin-harlanzw: ^0.12.0
  execa: ^9.6.1
  fuse.js: ^7.3.0
  magic-string: ^0.30.21
  nuxt: ^4.4.2
  nuxt-site-config: ^4.0.7
  nuxtseo-layer-devtools: ^5.1.2
  nuxtseo-shared: ^5.1.2
  ofetch: ^1.5.1
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  radix3: ^1.1.2
  shiki: ^4.0.2
  sirv: ^3.0.2
  std-env: ^4.0.0
  typescript: 6.0.2
  ufo: ^1.6.3
  ultrahtml: ^1.6.0
  unbuild: ^3.6.1
  unstorage: ^1.17.5
  vitest: ^4.1.4
  vue: ^3.5.32
  vue-eslint-parser: ^10.4.0
  vue-router: ^5.0.4
  vue-tsc: ^3.2.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - vue-demi
trustPolicyIgnoreAfter: 262800
