name: Test

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Prepare
        run: pnpm dev:prepare

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
